---// DoAlwaysTestPlan.lua
---// Copyright (c) 2023 Heatblur Simulations. All rights reserved.

local Class = require('base.Class')
local Plan = require('base.Plan')
local Math = require('base.Math')
local Utilities = require ('base.Utilities')

local DoAlwaysTestPlan = Class(Plan)

function DoAlwaysTestPlan:Constructor()
	Plan.Constructor(self)
end

function DoAlwaysTestPlan:Tick()
--     local g_force = jester.awareness:GetObservation( "g_force" )
--     local airport_dist = jester.awareness:GetObservation( "distance_to_nearest_airfield" )
--     local alt_above_airport = jester.awareness:GetObservation( "height_above_airfield" )
--     local on_ground = jester.awareness:GetObservation( "touching_ground" )
--     local fuel_dumping = jester.awareness:GetObservation( "Fuel Dumping" )
--     local tas = jester.awareness:GetObservation( "true_airspeed" )
--     local ias = jester.awareness:GetObservation( "indicated_airspeed" )
--     local alt = jester.awareness:GetObservation( "barometric_altitude" )
--     local gs = jester.awareness:GetObservation( "ground_speed" )
--     local velocity_ned_vector = jester.awareness:GetObservation("gods_velocity_ned")
--     	local velocity_ned_x = (velocity_ned_vector and velocity_ned_vector.x) or mps(0)
--     	local velocity_ned_y = (velocity_ned_vector and velocity_ned_vector.y) or mps(0)
--     	local velocity_ned_z = (velocity_ned_vector and velocity_ned_vector.z) or mps(0)
--     local ang_velocity_ned_vector = jester.awareness:GetObservation("gods_angular_velocity_ned")
--     	local ang_velocity_ned_x = (ang_velocity_ned_vector and ang_velocity_ned_vector.x) or degps(0)
--     	local ang_velocity_ned_y = (ang_velocity_ned_vector and ang_velocity_ned_vector.y) or degps(0)
--     	local ang_velocity_ned_z = (ang_velocity_ned_vector and ang_velocity_ned_vector.z) or degps(0)
-- local inverted = jester.awareness:GetObservation( "is_inverted" )
-- local aoa = jester.awareness:GetObservation( "angle_of_attack" )
--     local ang_velocity_body_vector = jester.awareness:GetObservation("gods_angular_velocity_body")
--     	local ang_velocity_body_x = (ang_velocity_body_vector and ang_velocity_body_vector.x) or degps(0)
--     	local ang_velocity_body_y = (ang_velocity_body_vector and ang_velocity_body_vector.y) or degps(0)
--     	local ang_velocity_body_z = (ang_velocity_body_vector and ang_velocity_body_vector.z) or degps(0)
-- local pitch = jester.awareness:GetObservation( "gods_pitch" )
-- local roll = jester.awareness:GetObservation( "gods_roll" )
-- local sl_temp = jester.awareness:GetObservation( "temperature_sea_level" )
-- local latitude = jester.awareness:GetObservation( "latitude" )
-- local longitude = jester.awareness:GetObservation( "longitude" )
-- local afterburner = jester.awareness:GetObservation( "Afterburner" )
-- local helmet_pilot = jester.awareness:GetObservation( "pilot_helmet_on" )
-- local helmet_wso = jester.awareness:GetObservation( "wso_helmet_on" )
-- local gear_right = jester.awareness:GetObservation( "right_gear_indicator" )
-- local gear_left = jester.awareness:GetObservation( "left_gear_indicator" )
-- local gear_nose = jester.awareness:GetObservation( "nose_gear_indicator" )
-- local rpm_left = jester.awareness:GetObservation( "rpm_left_engine" )
-- local rpm_right = jester.awareness:GetObservation( "rpm_right_engine" )
-- local cockpit_pressure = jester.awareness:GetObservation( "cockpit_pressure" )
-- local wso_canopy_light = jester.awareness:GetObservation( "wso_canopy_light" )
-- local heat_light = jester.awareness:GetObservation( "heat_light" )
-- local align_light_blinking = jester.awareness:GetObservation( "align_light_blinking" )
-- local align_light_stdy = jester.awareness:GetObservation( "align_light_stdy" )
-- local gear_front_oleo = jester.awareness:GetObservation( "front_oleo_compression" )
-- local gear_left_oleo = jester.awareness:GetObservation( "left_oleo_compression" )
-- local gear_right_oleo = jester.awareness:GetObservation( "right_oleo_compression" )
-- local gear_front_oleo_delta = jester.awareness:GetObservation( "front_oleo_rate" )
-- local gear_left_oleo_delta = jester.awareness:GetObservation( "left_oleo_rate" )
-- local gear_right_oleo_delta = jester.awareness:GetObservation( "right_oleo_rate" )

--     local log_message = string.format("G-force = %.2f", g_force.value or 0)
--     local log_message = string.format("Touching Ground: %s", tostring(on_ground))
--     local log_message2 = string.format("TAS = %.2f kt", tas.value or 0)
--     local log_message3 = string.format("IAS = %.2f kt", ias.value or 0)
--     local log_message4 = string.format("Alt = %.2f ft", alt.value or 0)
--     local log_message5 = string.format("Ground speed: %s", gs.value or 0)
--     local log_message6 = string.format("Vned  x:%s; y:%s; z:%s", velocity_ned_x.value or 0, velocity_ned_y.value or 0, velocity_ned_z.value or 0)
--     local log_message7 = string.format("Vrot  x:%s; y:%s; z:%s", ang_velocity_ned_x.value or 0, ang_velocity_ned_y.value or 0, ang_velocity_ned_z.value or 0)
--     local log_message8 = string.format("Is Inverted: %s", tostring(inverted))
--     local log_message9 = string.format("AOA = %.1f deg", aoa.value or 0)
--     local log_message10 = string.format("Vrot [body]  x:%s; y:%s; z:%s", ang_velocity_body_x.value or 0, ang_velocity_body_y.value or 0, ang_velocity_body_z.value or 0)
--     local log_message11 = string.format("Pitch = %.1f deg", pitch.value or 0)
--     local log_message12 = string.format("Roll = %.1f deg", roll.value or 0)
--     local log_message13 = string.format("SL temp = %.1f C", sl_temp.value or 0)
--     local log_message14 = string.format("latitude = %.2f rad", latitude.value or 0)
--     local log_message15 = string.format("longitude = %.2f rad", longitude.value or 0)
--     local log_message16 = string.format("Afterburner: %s", tostring(afterburner) )
--     local log_message17 = string.format("Helmet Pilot: %s", tostring(helmet_pilot) )
--     local log_message18 = string.format("Helmet WSO: %s", tostring(helmet_wso) )
--     local log_message19 = string.format("Left Gear: %.2f", gear_left or 0 )
--     local log_message20 = string.format("Right Gear: %.2f", gear_right or 0 )
--     local log_message21 = string.format("Nose Gear: %.2f", gear_nose or 0 )
--     local log_message22 = string.format("RMP Left: %.2f", rpm_left.value or 0 )
--     local log_message23 = string.format("RMP Right: %.2f", rpm_right.value or 0 )
--     local log_message24 = string.format("Cockpit Pressure: %.2f ft", cockpit_pressure.value or 0 )
--     local log_message25 = string.format( "Canopy Light: %s", tostring(wso_canopy_light) )
--     local log_message26 = string.format( "INS Heat Light: %s", tostring(heat_light) )
--     local log_message27 = string.format( "INS Align Light steady: %s", tostring(align_light_stdy) )
--     local log_message28 = string.format( "INS Align Light blinking: %s", tostring(align_light_blinking) )
--     local log_message29 = string.format( "Gear Oleo front: %.2f", gear_front_oleo or 0 )
--     local log_message30 = string.format( "Gear Oleo left: %.2f", gear_left_oleo or 0 )
--     local log_message31 = string.format( "Gear Oleo right: %.2f", gear_right_oleo or 0 )
--     local log_message32 = string.format( "Gear Oleo delta front: %.2f", gear_front_oleo_delta or 0 )
--     local log_message33 = string.format( "Gear Oleo delta left: %.2f", gear_left_oleo_delta or 0 )
--     local log_message34 = string.format( "Gear Oleo delta right: %.2f", gear_right_oleo_delta or 0 )
--     local log_message35 = string.format( "Fuel dumping: %s", tostring(fuel_dumping) )
--     local log_message36 = string.format("Airport dist = %.1f m", airport_dist.value or 0)
--     local log_message37 = string.format("Alt above airport = %.1f m", alt_above_airport.value or 0)

--  	Log( log_message )
--  	Log( log_message2 )
--  	Log( log_message3 )
--  	Log( log_message4 )
--  	Log( log_message5 )
--  	Log( log_message6 )
--  	Log( log_message7 )
--  	Log( log_message8 )
--  	Log( log_message9 )
--  	Log( log_message10 )
--  	Log( log_message11 )
--  	Log( log_message12 )
--  	Log( log_message13 )
--  	Log( log_message14 )
--  	Log( log_message15 )
--  	Log( log_message16 )
--  	Log( log_message17 )
--  	Log( log_message18 )
--  	Log( log_message19 )
--  	Log( log_message20 )
--  	Log( log_message21 )
--  	Log( log_message22 )
--  	Log( log_message23 )
--   	Log( log_message24 )
--   	Log( log_message25 )
--   	Log( log_message26 )
--   	Log( log_message27 )
--   	Log( log_message28 )
--   	Log( log_message29 )
--   	Log( log_message30 )
--   	Log( log_message31 )
--   	Log( log_message32 )
--   	Log( log_message33 )
--   	Log( log_message34 )
--   	Log( log_message35 )
--   	Log( log_message36 )
--   	Log( log_message37 )

end

DoAlwaysTestPlan:Seal()
return DoAlwaysTestPlan
